services:
  # Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./frontend:/app/frontend

  # Backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo-db
    env_file:
      - ./backend/.env.dev
    networks:
      - app-network
    volumes:
      - ./backend/src:/app/backend/src
      - ./backend/tsconfig.json:/app/backend/tsconfig.json

  # MongoDB (Database)
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    networks:
      - app-network
    volumes:
      - mongo-db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

# Networks to facilitate communication between services
networks:
  app-network:
    driver: bridge

# Volumes for data persistence across containers
volumes:
  mongo-db-data:
